### ISSUE TITLE
am I idiot?

### ISSUE THREAD

**Issue by Piplup7575** [glixzzy/quickz#1]
I'm probaly not understanding how this works or what it does but it doesnt seem to work on my end

https://user-images.githubusercontent.com/88395302/149668623-baad5ae6-d3eb-4160-8a8e-821b3b4b82a7.mp4

is it supposted to be for blooket? or am i an idiot, the readme says nothing

**Comment by glixzzy** [comment]
This isn’t for blooket.

**Comment by Piplup7575** [comment]
oh ok so i am idiot
